### ISSUE TITLE
iPhone 6s CPU 占用 116%

### ISSUE THREAD

**Issue by yinjimmy** [IppClub/Dorothy-SSR#2]
![image](https://user-images.githubusercontent.com/5056328/41082621-842ec0c2-6a61-11e8-9d7f-00e6098d5ddf.png)

**Comment by pigpigyyy** [comment]
VSync没开的时候FPS会狂飙，BGFX的render back end换成OpenGL应该就不占这么多。

**Comment by pigpigyyy** [comment]
手机游戏别做了，没意思，掌机主机PC游戏质量多高啊，可以玩一辈子。
